name: NLRL
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cloudpickle=3.0.0
  - comm=0.2.2
  - debugpy=1.8.11
  - decorator=5.2.1
  - deprecated=1.2.13
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - farama-notifications=0.0.4
  - filelock=3.17.0
  - fsspec=2024.12.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=9.3.0
  - ipython_pygments_lexers=1.1.1
  - jax-jumpy=1.0.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - libabseil=20250127.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.29
  - libprotobuf=5.29.3
  - libsodium=1.0.18
  - libtorch=2.5.1
  - libuv=1.48.0
  - llvm-openmp=14.0.6
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=3.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.5.0
  - opentelemetry-api=1.30.0
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - pytorch=2.5.1
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=78.1.1
  - six=1.17.0
  - sleef=3.5.1
  - sqlite=3.45.3
  - stack_data=0.6.3
  - sympy=1.13.3
  - tk=8.6.14
  - tornado=6.5
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - wrapt=1.17.0
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - absl-py==2.2.2
      - ale-py==0.11.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - certifi==2025.4.26
      - contourpy==1.3.2
      - cycler==0.12.1
      - distro==1.9.0
      - fonttools==4.58.0
      - grpcio==1.71.0
      - gymnasium==1.1.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - jiter==0.10.0
      - kiwisolver==1.4.8
      - markdown==3.8
      - markdown-it-py==3.0.0
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - openai==1.82.0
      - opencv-python==4.11.0.86
      - pandas==2.2.3
      - pillow==11.2.1
      - protobuf==6.30.2
      - psutil==7.0.0
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pygame==2.6.1
      - pyparsing==3.2.3
      - pytz==2025.2
      - rich==14.0.0
      - sniffio==1.3.1
      - stable-baselines3==2.6.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tqdm==4.67.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - werkzeug==3.1.3
